# Generated by Django 4.0.6 on 2022-10-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('percapitaApp', '0002_itempurchase_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempurchase',
            name='item',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
